[inference]
input_dir = "inference/input"
output_dir = "inference/output"

[data]
train_path = "dataset/train.csv"
test_path = "dataset/test.csv"
intermediate_data_dir = "intermediate"

[alert]
sender_email = "your@email.com"
sender_password = "yourpassword"
to_email = "recipient@email.com"